services:
  serge:
    image: serge
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./web:/usr/src/app/web/:z
      - ./api:/usr/src/app/api/:z
      - datadb2:/data/db
      - weights:/usr/src/app/weights/
      - /etc/localtime:/etc/localtime:ro
    command: ["sh", "-c", "pip install debugpy -t /tmp && /usr/src/app/dev.sh"]
    ports:
      - 8008:8008
      - 9124:9124
      - 5678:5678

volumes:
  datadb2:
  weights:
