version: "3.9"
services:
  api:
    build: 
      context: ./api
      dockerfile: ./Dockerfile.api
    volumes:
      - ./api:/usr/src/app/
      - weights:/usr/src/app/weights/
      - /etc/localtime:/etc/localtime:ro 
    depends_on:
      - mongodb
      - nginx
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9124 --root-path /api/

  mongodb:
      image: mongo:6.0.4-jammy
      ports:
        - "27017"
      volumes:
        - data:/data/db

  web:
    restart: on-failure
    build:
      context: ./web
      dockerfile: ./Dockerfile.web
    ports:
      - 9123:9123
    volumes:
      - ./web:/usr/src/app/
      - /usr/src/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 9123
    depends_on:
      - nginx
      - api
  nginx:
    build: 
      context: ./nginx
      dockerfile: ./Dockerfile.nginx 
    ports:
     - "${PORT}:80"

volumes:
  data:
  weights: