name: Cleanup untagged Docker images

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * *'

jobs:
  purge-untagged-images:
    if: ${{ github.repository_owner == 'nsarrazin' }}
    name: Delete untagged images from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 250
          delete-only-untagged-versions: true
